[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "yelp-analysis"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "numpy",
    "pyyaml",
    "pyarrow",
    "google-cloud-storage",
    "google-cloud-bigquery",
]

[tool.setuptools.packages.find]
where = ["src"]